packages:
- '.'
extra-deps:
- gi-cairo-connector-0.1.1
- gtk-sni-tray-0.1.8.1
- github: jchia/xdg-desktop-entry
  commit: df3b41d9f3c5b461b94ccb325bcbf4b049560d92

resolver: lts-22.8

allow-newer: true

nix:
  packages:
    - cairo
    - gcc
    - gnome2.pango
    - gobjectIntrospection
    - gtk3
    - hicolor-icon-theme
    - libdbusmenu-glib
    - libdbusmenu-gtk3
    - libxml2
    - pkgconfig
    - x11
    - xorg.libX11
    - xorg.libXScrnSaver
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
    - zlib
